In [2]:
import cv2
import numpy as np

In [3]:

def dilate_mask(mask, kernel_size=5, iterations=1):
    """
    세그멘테이션 마스크를 넓히는 함수

    :param mask: 이진 세그멘테이션 마스크 (numpy array)
    :param kernel_size: 커널 크기, 기본값은 5
    :param iterations: 팽창 연산 반복 횟수, 기본값은 1
    :return: 넓어진 세그멘테이션 마스크 (numpy array)
    """
    # 팽창 연산에 사용할 커널 정의
    kernel = np.ones((kernel_size, kernel_size), np.uint8)

    # 팽창 연산 수행
    dilated_mask = cv2.dilate(mask, kernel, iterations=iterations)
    
    return dilated_mask

In [4]:
!pwd

/home/sypark/ZSAS-SYHW


In [5]:
mask_height = 200
mask_width = 200

In [6]:
# 흰색 배경에 검은색 원 생성
mask = np.zeros((mask_height, mask_width), dtype=np.uint8)
cv2.circle(mask, (mask_width // 2, mask_height // 2), 50, (255), -1)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [7]:
# 세그멘테이션 마스크 저장
cv2.imwrite('example_segmentation_mask.png', mask)

True

In [9]:
mask

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [12]:
# 예시로 사용할 세그멘테이션 마스크 로드
mask = cv2.imread('example_segmentation_mask.png', cv2.IMREAD_GRAYSCALE)

In [13]:
# 마스크 팽창
dilated_mask = dilate_mask(mask, kernel_size=5, iterations=2)


In [14]:
dilated_mask

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [15]:
# 결과 저장
cv2.imwrite('path_to_save_dilated_mask.png', dilated_mask)

True